version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password

  collector:
    build: ./collector
    depends_on:
      - db

  reporter:
    build: ./reporter
    depends_on:
      - db


        ##Multi-service orchestartion
